import { defineConfig, presetUno } from 'unocss'

export default defineConfig({
  presets: [presetUno()],
  theme: {
    colors: {
      primary: '#526FE8',
      'primary-hover': '#435FD0',
      'primary-light': 'rgba(82, 111, 232, 0.08)',
      'primary-soft': '#EEF1FF',
      accent: '#8EA5FF',
      success: '#16805D',
      warning: '#B7791F',
      error: '#C2414B',
      info: '#3569C8',
      'bg-page': '#F5F7FC',
      'bg-card': '#ffffff',
      'bg-sidebar': '#ffffff',
      'bg-sidebar-hover': '#F5F7FC',
      'text-primary': '#29365C',
      'text-secondary': '#667085',
      'text-tertiary': '#8A93A8',
      'text-sidebar': '#29365C',
      'text-sidebar-active': '#526FE8',
      'border-color': '#E5E9F2',
    },
  },
  shortcuts: {
    'page-container': 'max-w-1440px mx-auto p-6',
    'card': 'bg-white rounded-xl border border-border-color shadow-sm p-6',
    'card-hover': 'card transition-all duration-200 hover:shadow-md',
    'btn-primary': 'bg-primary text-white px-4 py-2 rounded-lg hover:bg-primary-hover transition-colors cursor-pointer',
    'input-field': 'w-full px-3 py-2 border border-border-color rounded-lg bg-white focus:border-primary focus:ring-2 focus:ring-primary-light outline-none transition-all',
    'sidebar-link': 'flex items-center gap-3 px-4 py-2.5 mx-2 rounded-lg text-text-primary hover:bg-bg-sidebar-hover transition-all duration-200',
    'sidebar-link-active': 'sidebar-link bg-primary-soft text-text-sidebar-active font-medium',
    'page-header': 'flex items-center justify-between mb-6',
    'page-title': 'text-xl font-semibold text-text-primary',
    'stat-card': 'card flex items-center gap-4',
    'stat-value': 'text-2xl font-bold text-text-primary',
    'stat-label': 'text-sm text-text-secondary',
  },
})
