-- 博主个人资料新增性格/星座与对外展示开关字段
ALTER TABLE bloggers ADD COLUMN personality VARCHAR(20) NOT NULL DEFAULT '';
ALTER TABLE bloggers ADD COLUMN zodiac VARCHAR(20) NOT NULL DEFAULT '';
ALTER TABLE bloggers ADD COLUMN show_email BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE bloggers ADD COLUMN show_city BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE bloggers ADD COLUMN show_zodiac BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE bloggers ADD COLUMN show_personality BOOLEAN NOT NULL DEFAULT TRUE;
